//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeHubDesktop.MultiLanguage.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeHubDesktop.MultiLanguage.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeHub is a platform for archiving the errors, bugs, and scripts you intend to share with others. 
        ///Desktop Version Work with CodeHub API..
        /// </summary>
        public static string AboutDec {
            get {
                return ResourceManager.GetString("AboutDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have Permission, Please Run app as Administrator or change application directory to another drive.
        /// </summary>
        public static string AdminError {
            get {
                return ResourceManager.GetString("AdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Access Error.
        /// </summary>
        public static string AdminErrorTitle {
            get {
                return ResourceManager.GetString("AdminErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter API Url....
        /// </summary>
        public static string APIUrl {
            get {
                return ResourceManager.GetString("APIUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Url.
        /// </summary>
        public static string APIUrlTitle {
            get {
                return ResourceManager.GetString("APIUrlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change language?.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        public static string CheckForUpdate {
            get {
                return ResourceManager.GetString("CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Snippet.
        /// </summary>
        public static string CreateSnippet {
            get {
                return ResourceManager.GetString("CreateSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Version.
        /// </summary>
        public static string CurrentVer {
            get {
                return ResourceManager.GetString("CurrentVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DataGridDate {
            get {
                return ResourceManager.GetString("DataGridDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DataGridDetail {
            get {
                return ResourceManager.GetString("DataGridDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string DataGridLanguage {
            get {
                return ResourceManager.GetString("DataGridLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string DataGridLink {
            get {
                return ResourceManager.GetString("DataGridLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string DataGridScript {
            get {
                return ResourceManager.GetString("DataGridScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SId.
        /// </summary>
        public static string DataGridSId {
            get {
                return ResourceManager.GetString("DataGridSId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string DataGridTitle {
            get {
                return ResourceManager.GetString("DataGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail....
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet Detail (Optional).
        /// </summary>
        public static string DetailTitle {
            get {
                return ResourceManager.GetString("DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer Mahdi Hosseini.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Link.
        /// </summary>
        public static string DownloadLink {
            get {
                return ResourceManager.GetString("DownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download New Update.
        /// </summary>
        public static string DownloadNewVer {
            get {
                return ResourceManager.GetString("DownloadNewVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error....
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeHub Desktop.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeHub.
        /// </summary>
        public static string GithubOrg {
            get {
                return ResourceManager.GetString("GithubOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string HamburgerMenuHeaderItem {
            get {
                return ResourceManager.GetString("HamburgerMenuHeaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Date.
        /// </summary>
        public static string HistoryDate {
            get {
                return ResourceManager.GetString("HistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string HistoryLanguage {
            get {
                return ResourceManager.GetString("HistoryLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string HistoryLink {
            get {
                return ResourceManager.GetString("HistoryLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using Latest Version.
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Menu Style.
        /// </summary>
        public static string ModernStyle {
            get {
                return ResourceManager.GetString("ModernStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        public static string NewVer {
            get {
                return ResourceManager.GetString("NewVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Found!.
        /// </summary>
        public static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cant find any version.
        /// </summary>
        public static string NoNewVersion {
            get {
                return ResourceManager.GetString("NoNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Hub.
        /// </summary>
        public static string PaneTitle {
            get {
                return ResourceManager.GetString("PaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published at.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Title....
        /// </summary>
        public static string Searchbar {
            get {
                return ResourceManager.GetString("Searchbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Snippet Id or Url....
        /// </summary>
        public static string SearchbarPlaceHolder {
            get {
                return ResourceManager.GetString("SearchbarPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Snippet By Id or Url.
        /// </summary>
        public static string SearchbarTitle {
            get {
                return ResourceManager.GetString("SearchbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Language....
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Snippet Language.
        /// </summary>
        public static string SelectLanguageTitle {
            get {
                return ResourceManager.GetString("SelectLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Snippets.
        /// </summary>
        public static string SettingStoreSnippet {
            get {
                return ResourceManager.GetString("SettingStoreSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Copied to Clipborad.
        /// </summary>
        public static string ShieldSubject {
            get {
                return ResourceManager.GetString("ShieldSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet History.
        /// </summary>
        public static string SnippetHistory {
            get {
                return ResourceManager.GetString("SnippetHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject....
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippet Title.
        /// </summary>
        public static string SubjectTitle {
            get {
                return ResourceManager.GetString("SubjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Snippets.
        /// </summary>
        public static string TabLocal {
            get {
                return ResourceManager.GetString("TabLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others Snippets.
        /// </summary>
        public static string TabOther {
            get {
                return ResourceManager.GetString("TabOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
